repos:

# pre-commit-hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # -   id: trailing-whitespace
    # -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: debug-statements
    # -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: check-ast
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
    -   id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-byte-order-marker
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks

# # flake8
# -   repo: https://github.com/PyCQA/flake8
#     rev: 7.0.0
#     hooks:
#     -   id: flake8

# # isort
# -   repo: https://github.com/pycqa/isort
#     rev: 5.13.2
#     hooks:
#     -   id: isort
#         name: isort (python)
#         # args: [--config=pyproject.toml]

# # pycln
# -   repo: https://github.com/hadialqattan/pycln
#     rev: v2.4.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
#     hooks:
#     -   id: pycln
#         name: pycln
#         args: [--config=pyproject.toml]

# black
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    # -   id: black-jupyter
    #     name: black-jupyter (python)
    #     args: [--config=pyproject.toml]
    #     # language_version: python3.10
    -   id: black
        name: black (python)
        args : [--config=pyproject.toml]
        # language_version: python3.10

# # pytest
# -   repo: local
#     hooks:
#     -   id: run_tests
#         language: script
#         name: run_tests
#         entry: .utils/pytest.sh
#         stage: [commit]
